function [priorlpp] = priorlpp(priorpars,pars)

%% This function computes the joint prior of the model and auxiliary parameters

[modpars,tau,histvec,alpha,lambda] = extractparms(pars);

priorlpp = sum(log(prior_exp(modpars(1:4),priorpars.ratepars(1:4)'))) ...
            + sum(log(prior_exp(modpars(5:6),priorpars.ratepars(5:6)'))) ...
            + sum(log(prior_chisq(tau,priorpars.taudf))) ...
            + sum(log(prior_normal(histvec(1),priorpars.hist1mu,priorpars.hist1var))) ...
            + sum(log(prior_lognorm(alpha,priorpars.alphashift',priorpars.alphamean',priorpars.alphavar'))) ...
            + sum(log(prior_chisq(lambda,priorpars.lambdasp')));

end