function rqt = RQ1d(u1,v1,w,a,b)


% u1=[0:0.1:1]
% v1=[0:0.1:1]
% w=0.2
% a=0
% b=1

if (size(u1,1)<size(u1,2))
    u1 = u1';
end

if (size(v1,1)<size(v1,2))
    v1 = v1';
end

u = repmat(u1,1,length(v1));
v = repmat(v1',length(u1),1);

rqt=(...
    (2.*w).*(min(v-w,u+w)-max(a+w,u-w))...
    .*(min(v-w,u+w)>max(a+w,u-w))...
    +(0.5.*min(a+w,min(v-w,u+w)).^2+(w-a).*min(a+w,min(v-w,u+w))...
    -0.5.*max(a-w,u-w).^2 -(w-a).*max(a-w,u-w))...
    .*(min(a+w,min(v-w,u+w))>max(a-w,u-w))...
    +((v+w).*min(v+w,u+w) - 0.5.*min(v+w,u+w).^2 ...
    -(v+w).*max(a+w,max(v-w,u-w))+ 0.5.*max(a+w,max(v-w,u-w)).^2)...
    .*(min(v+w,u+w)>max(a+w,max(v-w,u-w)))...
    + ((v-a).*min(a+w,u+w) - (v-a).*max(v-w,u-w))...
    .*(min(a+w,u+w)>max(v-w,u-w)) ...
    );


end