function qqt = QQ1d_un(u1,v1,lambda,a,b)

if (size(u1,1)<size(u1,2))
    u1 = u1';
end

if (size(v1,1)<size(v1,2))
    v1 = v1';
end

u = repmat(u1,1,length(v1));
v = repmat(v1',length(u1),1);

qqt=((4.*lambda.^2).*(min(u,v)-a-2.*lambda).*(min(u,v)>(a+2.*lambda))...
    +(2.*lambda).*((v+lambda).*min(u-lambda,v+lambda) - 0.5.*min(u-lambda,v+lambda).^2 - (v+lambda).*max(a+lambda,v-lambda) + 0.5.*max(a+lambda,v-lambda).^2).*(min(u-lambda,v+lambda)>max(a+lambda,v-lambda))...
    +((1/3).*min(a+lambda,min(u-lambda,v-lambda)).^3 + (lambda-a).*min(a+lambda,min(u-lambda,v-lambda)).^2 + (lambda-a).^2.*min(a+lambda,min(u-lambda,v-lambda))-(1/3).*(a-lambda).^3 - (lambda-a).*(a-lambda).^2 - (lambda-a).^2.*(a-lambda)).*(min(a+lambda,min(u-lambda,v-lambda))>(a-lambda))...
    +(v-a).*(0.5.*min(a+lambda,u-lambda).^2 + (lambda-a).*min(a+lambda,u-lambda)- 0.5.*(v-lambda).^2 - (lambda-a).*(v-lambda)).*(min(a+lambda,u-lambda)>(v-lambda))...
    +(2.*lambda).*((u+lambda).*min(u+lambda,v-lambda)-0.5.*min(u+lambda,v-lambda).^2-(u+lambda).*max(a+lambda,u-lambda) + 0.5.*max(a+lambda,u-lambda).^2).*(min(u+lambda,v-lambda)>max(a+lambda,u-lambda))...
    +((u+lambda).*(v+lambda).*min(u+lambda,v+lambda) - 0.5.*(u+v+2.*lambda).*min(u+lambda,v+lambda).^2 + (1/3).*min(u+lambda,v+lambda).^3 - (u+lambda).*(v+lambda).*max(a+lambda,max(u-lambda,v-lambda)) + 0.5.*(u+v+2.*lambda).*max(a+lambda,max(u-lambda,v-lambda)).^2 - (1/3).*max(a+lambda,max(u-lambda,v-lambda)).^3).*(min(u,v)>max(a,max(u-2.*lambda,v-2.*lambda)))...
    +(u-a).*(0.5.*min(a+lambda,v-lambda).^2 + (lambda-a).*min(a+lambda,v-lambda)- 0.5.*(u-lambda).^2 - (lambda-a).*(u-lambda)).*(min(a+lambda,v-lambda)>(u-lambda))...
    +(u-a).*(v-a).*(a+2.*lambda-max(u,v)).*(a+2.*lambda>max(u,v))...
    );
        
end
